name: Deploy code to Lambda
on: push

env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup python 3.8'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Zip it all'
        run: |
          mkdir -p zip_folder
          cp -R src/* zip_folder
          pip install -r requirements.txt --target=zip_folder
          cd zip_folder
          zip -r ../${REPO_NAME}.zip .
      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '>=0.13.0 <0.14.0'
      - name: 'Terraform init'
        working-directory: terraform
        run: terraform init
      - name: 'Terraform validate'
        working-directory: terraform
        run: terraform validate
      - name: 'Terraform plan'
        working-directory: terraform
        run: |
          terraform plan -out="${REPO_NAME}.tfplan"
      - name: 'Terraform apply'
        working-directory: terraform
        run: terraform apply -auto-approve "${REPO_NAME}.tfplan"