name: Deploy code to Lambda
on: push
  push:
    branches:
      - 'master'

env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   REPO_NAME: ${{ github.event.repository.name }}

jobs:
  push-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup python 3.8'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Zip it all'
        run: |
          mkdir -p zip_folder
          cp -R src/* zip_folder
          pip install -r requirements.txt --target=zip_folder
          cd zip_folder
          zip -r ../${REPO_NAME}.zip .
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: 'terraform'
          tf_actions_comment: true
          args: '-auto-approve'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}